[project]
name = "leetcode-calculator"
version = "0.1.0"
description = "A tool to predict when you'll reach your LeetCode points goal!"
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
    "pytest>=8.3.5",
]